// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HotelRatingServiceML.Model
{
    public class ModelInput
    {
        [ColumnName("Review"), LoadColumn(0)]
        public string Review { get; set; }


        [ColumnName("Rating"), LoadColumn(1)]
        public string Rating { get; set; }


    }
}